import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>ServCraft Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon56@2x.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://servcraft.co.za" rel="noopener noreferrer" target={"_blank"}>ServCraft!</a>
        </h1>

        <p className={styles.description}>
          Please feel free to complete the assessment tasks itemised below.
        </p>

        <ol>
          <li className={styles.code}>Create a new page called &quot;test.tsx&quot;
            <ol type='a'>
              <li  className={styles.code}>
                At the bottom of this page, add a button that navigates to the &quot;test.tsx&quot; page
              </li>
              <li  className={styles.code}>
                In &quot;test.tsx&quot;, add a button that navigates back home
              </li>
            </ol>
          </li>
          <li className={styles.code}>
            On &quot;test.tsx&quot; create a table that is dynamically generated from the json data set stored in &quot;data/testData.json&quot;
            <ol type='a'>
              <li  className={styles.code}>
                On click, each row of the table will navigate to a details page pertaining to the data in the row that was clicked
              </li>
              <li  className={styles.code}>
                This would then need a new page to display the details of the row
              </li>
              <li  className={styles.code}>
                Add a button to the details page that increments the person&apos;s age by one year
              </li>
            </ol>
          </li>
        </ol>

     
      </main>

      <footer className={styles.footer}>
        <a
          href="https://servcraft.co.za"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo-type-blue.svg" alt="ServCraft Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
